# Generated by Django 6.0 on 2025-12-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Processing'), ('STAGING', 'Staging Data'), ('STAGED', 'Data Staged'), ('PROCESSING', 'Processing Items'), ('COMPLETED', 'Completed Successfully'), ('FAILED', 'Failed with Errors'), ('PARTIAL', 'Partially Completed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
