# Generated by Django 6.0 on 2025-12-18 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingest", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionbatch",
            name="uploaded_by",
            field=models.ForeignKey(
                help_text="User who uploaded this file",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facultyentry",
            name="batch",
            field=models.ForeignKey(
                help_text="Which ingestion batch this entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_entries",
                to="ingest.ingestionbatch",
            ),
        ),
        migrations.AddField(
            model_name="processingfailure",
            name="batch",
            field=models.ForeignKey(
                help_text="Which batch this failure occurred in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="failures",
                to="ingest.ingestionbatch",
            ),
        ),
        migrations.AddField(
            model_name="qlikentry",
            name="batch",
            field=models.ForeignKey(
                help_text="Which ingestion batch this entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qlik_entries",
                to="ingest.ingestionbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionbatch",
            index=models.Index(
                fields=["status", "source_type"], name="ingest_batc_status_1e2f9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionbatch",
            index=models.Index(
                fields=["uploaded_by", "uploaded_at"],
                name="ingest_batc_uploade_11b642_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="facultyentry",
            index=models.Index(
                fields=["batch", "processed"], name="ingest_facu_batch_i_86aea6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facultyentry",
            index=models.Index(
                fields=["material_id"], name="ingest_facu_materia_4a026d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingfailure",
            index=models.Index(
                fields=["batch", "created_at"], name="ingest_fail_batch_i_2171bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="processingfailure",
            index=models.Index(
                fields=["error_type"], name="ingest_fail_error_t_6d23f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qlikentry",
            index=models.Index(
                fields=["batch", "processed"], name="ingest_qlik_batch_i_6a140b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="qlikentry",
            index=models.Index(
                fields=["material_id"], name="ingest_qlik_materia_19fbfc_idx"
            ),
        ),
    ]
