# Generated by Django 6.0 on 2025-12-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculties', models.JSONField(help_text='List of faculty abbreviations that were exported')),
                ('export_all', models.BooleanField(default=False, help_text='Whether all faculties were exported')),
                ('output_dir', models.CharField(help_text='Directory where exports were written', max_length=512)),
                ('files_created', models.JSONField(default=list, help_text='List of file paths that were created')),
                ('total_items', models.IntegerField(default=0, help_text='Total number of items exported')),
                ('total_files', models.IntegerField(default=0, help_text='Total number of Excel files created')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When export started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When export finished', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional export metadata (buckets, backup info, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(help_text='User who triggered this export', on_delete=django.db.models.deletion.PROTECT, related_name='triggered_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export History',
                'verbose_name_plural': 'Export Histories',
                'db_table': 'ingest_export_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='ingest_expo_status_cb966d_idx'), models.Index(fields=['triggered_by', 'created_at'], name='ingest_expo_trigger_6ec78d_idx')],
            },
        ),
    ]
