# Generated by Django 6.0 on 2025-12-27 17:16

from django.db import migrations


def create_test_user(apps, schema_editor):
    """Create a test user for Playwright UI tests and manual testing."""
    User = apps.get_model('users', 'User')

    # Only create if doesn't exist (allow re-running migration)
    if not User.objects.filter(username="testuser").exists():
        User.objects.create_user(
            username="testuser",
            password="testpass123",
            email="test@example.com",
            is_staff=True,
            is_superuser=True,
        )


def remove_test_user(apps, schema_editor):
    """Remove the test user when rolling back migration."""
    User = apps.get_model('users', 'User')
    User.objects.filter(username="testuser").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_user, remove_test_user),
    ]

