# Generated by Django 6.0 on 2025-12-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(help_text="Dictionary of changed fields: {'field_name': {'old': ..., 'new': ...}}")),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the change occurred')),
                ('change_source', models.CharField(choices=[('QLIK', 'Qlik Ingestion'), ('FACULTY', 'Faculty Ingestion'), ('MANUAL', 'Manual Edit'), ('ENRICHMENT', 'Enrichment Process'), ('MIGRATION', 'Data Migration'), ('SYSTEM', 'System Process')], help_text='Source of the change', max_length=20)),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'db_table': 'change_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyrightItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('material_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, db_index=True, max_length=2048, null=True)),
                ('filehash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('filetype', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('doc', 'Word'), ('xlsx', 'Excel'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('author', models.CharField(blank=True, max_length=2048, null=True)),
                ('publisher', models.CharField(blank=True, max_length=2048, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=2048, null=True)),
                ('course_code', models.CharField(blank=True, max_length=2048, null=True)),
                ('course_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished'), ('Deleted', 'Deleted')], default='Published', max_length=50)),
                ('classification', models.CharField(choices=[('open access', 'open access'), ('korte overname', 'korte overname'), ('middellange overname', 'middellange overname'), ('lange overname', 'lange overname'), ('eigen materiaal - powerpoint', 'eigen materiaal - powerpoint'), ('eigen materiaal - titelindicatie', 'eigen materiaal - titelindicatie'), ('eigen materiaal - overig', 'eigen materiaal - overig'), ('eigen materiaal', 'eigen materiaal'), ('onbekend', 'onbekend'), ('niet geanalyseerd', 'niet geanalyseerd'), ('in onderzoek', 'in onderzoek'), ('verwijderverzoek verstuurd', 'verwijderverzoek verstuurd'), ('licentie beschikbaar', 'licentie beschikbaar')], default='niet geanalyseerd', max_length=100)),
                ('ml_classification', models.CharField(choices=[('open access', 'open access'), ('korte overname', 'korte overname'), ('middellange overname', 'middellange overname'), ('lange overname', 'lange overname'), ('eigen materiaal - powerpoint', 'eigen materiaal - powerpoint'), ('eigen materiaal - titelindicatie', 'eigen materiaal - titelindicatie'), ('eigen materiaal - overig', 'eigen materiaal - overig'), ('eigen materiaal', 'eigen materiaal'), ('onbekend', 'onbekend'), ('niet geanalyseerd', 'niet geanalyseerd'), ('in onderzoek', 'in onderzoek'), ('verwijderverzoek verstuurd', 'verwijderverzoek verstuurd'), ('licentie beschikbaar', 'licentie beschikbaar')], default='niet geanalyseerd', max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=2048, null=True)),
                ('in_collection', models.BooleanField(blank=True, null=True)),
                ('picturecount', models.IntegerField(default=0)),
                ('reliability', models.IntegerField(default=0)),
                ('pages_x_students', models.IntegerField(default=0)),
                ('count_students_registered', models.IntegerField(default=0)),
                ('pagecount', models.IntegerField(default=0)),
                ('wordcount', models.IntegerField(default=0)),
                ('workflow_status', models.CharField(choices=[('ToDo', 'To Do'), ('InProgress', 'In Progress'), ('Done', 'Done')], db_index=True, default='ToDo', max_length=50)),
                ('manual_classification', models.CharField(choices=[('open access', 'open access'), ('korte overname', 'korte overname'), ('middellange overname', 'middellange overname'), ('lange overname', 'lange overname'), ('eigen materiaal - powerpoint', 'eigen materiaal - powerpoint'), ('eigen materiaal - titelindicatie', 'eigen materiaal - titelindicatie'), ('eigen materiaal - overig', 'eigen materiaal - overig'), ('eigen materiaal', 'eigen materiaal'), ('onbekend', 'onbekend'), ('niet geanalyseerd', 'niet geanalyseerd'), ('in onderzoek', 'in onderzoek'), ('verwijderverzoek verstuurd', 'verwijderverzoek verstuurd'), ('licentie beschikbaar', 'licentie beschikbaar')], default='onbekend', max_length=2048)),
                ('manual_identifier', models.CharField(blank=True, max_length=2048, null=True)),
                ('scope', models.CharField(blank=True, max_length=50, null=True)),
                ('v2_manual_classification', models.CharField(choices=[('Ja (open licentie)', 'Ja (Open Licentie)'), ('Ja (eigen werk)', 'Ja (Eigen Werk)'), ('Ja (easy access)', 'Ja (Easy Access)'), ('Nee', 'Nee'), ('Onbekend', 'Onbekend'), ('Ja (bibilotheek licentie)', 'Ja (Bibliotheek Licentie)'), ('Ja (directe toestemming)', 'Ja (Directe Toestemming)'), ('Ja (Publiek domein)', 'Ja (Publiek Domein)'), ('Ja (studentwerk)', 'Ja (Studentwerk)'), ('Ja (anders)', 'Ja (Anders)'), ('Ja (directe toestemming) - tijdelijk', 'Ja (Directe Toestemming) - Tijdelijk'), ('Ja (bibilotheek licentie)- tijdelijk', 'Ja (Bibliotheek Licentie) - Tijdelijk'), ('Ja (anders) - tijdelijk', 'Ja (Anders) - Tijdelijk'), ('Nee (Link beschikbaar)', 'Nee (Link Beschikbaar)'), ('Nee (studentwerk)', 'Nee (Studentwerk)')], db_index=True, default='Onbekend', max_length=100)),
                ('v2_overnamestatus', models.CharField(choices=[('Overname (inbreukmakende)', 'Inbreukmakend'), ('Overname (andere)', 'Overname (Andere)'), ('Geen overname', 'Geen Overname'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=100)),
                ('v2_lengte', models.CharField(choices=[('Kort', 'Kort'), ('Middellang', 'Middellang'), ('Lang', 'Lang'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=50)),
                ('auditor', models.CharField(blank=True, max_length=2048, null=True)),
                ('last_change', models.DateTimeField(blank=True, null=True)),
                ('file_exists', models.BooleanField(blank=True, null=True)),
                ('last_canvas_check', models.DateTimeField(blank=True, null=True)),
                ('canvas_course_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cursuscode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('internal_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=2048)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('programme_text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hierarchy_level', models.IntegerField(help_text='0=Uni, 1=Faculty, 2=Dept')),
                ('name', models.CharField(db_index=True, max_length=2048)),
                ('abbreviation', models.CharField(db_index=True, max_length=255)),
                ('full_abbreviation', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegacyCopyrightItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('material_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('filehash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=2048, null=True)),
                ('manual_classification', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MissingCourse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cursuscode', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('input_name', models.CharField(db_index=True, max_length=2048, unique=True)),
                ('main_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=2048, null=True)),
                ('people_page_url', models.URLField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
