# Generated by Django 6.0 on 2025-12-16 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cursuscode', models.BigIntegerField(primary_key=True, serialize=False)),
                ('internal_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=2048)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('programme_text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('hierarchy_level', models.IntegerField(help_text='0=Uni, 1=Faculty, 2=Dept')),
                ('name', models.CharField(db_index=True, max_length=2048)),
                ('abbreviation', models.CharField(db_index=True, max_length=255)),
                ('full_abbreviation', models.CharField(max_length=2048, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.organization')),
            ],
            options={
                'unique_together': {('name', 'abbreviation')},
            },
        ),
        migrations.CreateModel(
            name='MissingCourse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cursuscode', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StagedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('target_material_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(choices=[('CRC', 'CRC Export'), ('SHEET', 'Faculty Excel Sheet')], max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CopyrightItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('material_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, db_index=True, max_length=2048, null=True)),
                ('filehash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('filetype', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('doc', 'Word'), ('xlsx', 'Excel'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('workflow_status', models.CharField(choices=[('ToDo', 'To Do'), ('InProgress', 'In Progress'), ('Done', 'Done')], db_index=True, default='ToDo', max_length=50)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished'), ('Deleted', 'Deleted')], default='Published', max_length=50)),
                ('classification', models.CharField(choices=[('open access', 'open access'), ('korte overname', 'korte overname'), ('middellange overname', 'middellange overname'), ('lange overname', 'lange overname'), ('eigen materiaal - powerpoint', 'eigen materiaal - powerpoint'), ('eigen materiaal - titelindicatie', 'eigen materiaal - titelindicatie'), ('eigen materiaal - overig', 'eigen materiaal - overig'), ('eigen materiaal', 'eigen materiaal'), ('onbekend', 'onbekend'), ('niet geanalyseerd', 'niet geanalyseerd'), ('in onderzoek', 'in onderzoek'), ('verwijderverzoek verstuurd', 'verwijderverzoek verstuurd'), ('licentie beschikbaar', 'licentie beschikbaar')], default='lange overname', max_length=100)),
                ('manual_classification', models.CharField(blank=True, max_length=2048, null=True)),
                ('v2_manual_classification', models.CharField(choices=[('Ja (open licentie)', 'Ja (Open Licentie)'), ('Ja (eigen werk)', 'Ja (Eigen Werk)'), ('Ja (easy access)', 'Ja (Easy Access)'), ('Nee', 'Nee'), ('Onbekend', 'Onbekend'), ('Ja (bibilotheek licentie)', 'Ja (Bibliotheek Licentie)'), ('Ja (directe toestemming)', 'Ja (Directe Toestemming)'), ('Ja (Publiek domein)', 'Ja (Publiek Domein)'), ('Ja (studentwerk)', 'Ja (Studentwerk)'), ('Ja (anders)', 'Ja (Anders)'), ('Ja (directe toestemming) - tijdelijk', 'Ja (Directe Toestemming) - Tijdelijk'), ('Ja (bibilotheek licentie)- tijdelijk', 'Ja (Bibliotheek Licentie) - Tijdelijk'), ('Ja (anders) - tijdelijk', 'Ja (Anders) - Tijdelijk'), ('Nee (Link beschikbaar)', 'Nee (Link Beschikbaar)'), ('Nee (studentwerk)', 'Nee (Studentwerk)')], db_index=True, default='Onbekend', max_length=100)),
                ('v2_overnamestatus', models.CharField(choices=[('Overname (inbreukmakende)', 'Inbreukmakend'), ('Overname (andere)', 'Overname (Andere)'), ('Geen overname', 'Geen Overname'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=100)),
                ('v2_lengte', models.CharField(choices=[('Kort', 'Kort'), ('Middellang', 'Middellang'), ('Lang', 'Lang'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=50)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('author', models.CharField(blank=True, max_length=2048, null=True)),
                ('publisher', models.CharField(blank=True, max_length=2048, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=2048, null=True)),
                ('course_code', models.CharField(blank=True, max_length=2048, null=True)),
                ('course_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('manual_identifier', models.CharField(blank=True, max_length=2048, null=True)),
                ('scope', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=2048, null=True)),
                ('in_collection', models.BooleanField(blank=True, null=True)),
                ('picturecount', models.IntegerField(default=0)),
                ('reliability', models.IntegerField(default=0)),
                ('pages_x_students', models.IntegerField(default=0)),
                ('count_students_registered', models.IntegerField(default=0)),
                ('pagecount', models.IntegerField(default=0)),
                ('wordcount', models.IntegerField(default=0)),
                ('canvas_course_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('file_exists', models.BooleanField(blank=True, null=True)),
                ('last_canvas_check', models.DateTimeField(blank=True, null=True)),
                ('infringement', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe'), ('undetermined', 'Undetermined')], default='undetermined', max_length=50)),
                ('possible_fine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='copyright_items', to='core.course')),
            ],
            options={
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.organization')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.organization',),
        ),
        migrations.CreateModel(
            name='ItemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('change_details', models.JSONField()),
                ('material_id', models.IntegerField(help_text='ID of the item in the copyright tool')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.copyrightitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyCopyrightItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('material_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('filehash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('filename', models.CharField(blank=True, max_length=2048, null=True)),
                ('manual_classification', models.CharField(blank=True, max_length=2048, null=True)),
                ('matched_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_matches', to='core.copyrightitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('input_name', models.CharField(db_index=True, max_length=2048, unique=True)),
                ('main_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=2048, null=True)),
                ('people_page_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('orgs', models.ManyToManyField(blank=True, related_name='personnel', to='core.organization')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses', through='core.CourseEmployee', to='core.person'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.faculty'),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.faculty'),
        ),
        migrations.AddIndex(
            model_name='copyrightitem',
            index=models.Index(fields=['workflow_status', 'faculty'], name='core_copyri_workflo_8404da_idx'),
        ),
    ]
