# Generated by Django 6.0 on 2025-12-16 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(help_text="Dictionary of changed fields: {'field_name': {'old': ..., 'new': ...}}")),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the change occurred')),
                ('change_source', models.CharField(choices=[('QLIK', 'Qlik Ingestion'), ('FACULTY', 'Faculty Ingestion'), ('MANUAL', 'Manual Edit'), ('ENRICHMENT', 'Enrichment Process'), ('MIGRATION', 'Data Migration'), ('SYSTEM', 'System Process')], help_text='Source of the change', max_length=20)),
                ('batch', models.ForeignKey(blank=True, help_text='Ingestion batch that caused this change (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='ingest.ingestionbatch')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change (null for system changes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(help_text='The item that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.copyrightitem')),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'db_table': 'change_logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['item', '-changed_at'], name='change_logs_item_id_07635f_idx'), models.Index(fields=['changed_by', '-changed_at'], name='change_logs_changed_90c830_idx'), models.Index(fields=['batch'], name='change_logs_batch_i_733b64_idx'), models.Index(fields=['change_source', '-changed_at'], name='change_logs_change__fed443_idx')],
            },
        ),
    ]
