# Generated by GitHub Copilot for Phase A cleanup

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_changelog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ItemUpdate",
        ),
        migrations.DeleteModel(
            name="StagedItem",
        ),
    ]
