# Generated by Django 6.0 on 2025-12-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_missingcourse_itemupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightitem',
            name='classification',
            field=models.CharField(choices=[('open access', 'open access'), ('korte overname', 'korte overname'), ('middellange overname', 'middellange overname'), ('lange overname', 'lange overname'), ('eigen materiaal - powerpoint', 'eigen materiaal - powerpoint'), ('eigen materiaal - titelindicatie', 'eigen materiaal - titelindicatie'), ('eigen materiaal - overig', 'eigen materiaal - overig'), ('eigen materiaal', 'eigen materiaal'), ('onbekend', 'onbekend'), ('niet geanalyseerd', 'niet geanalyseerd'), ('in onderzoek', 'in onderzoek'), ('verwijderverzoek verstuurd', 'verwijderverzoek verstuurd'), ('licentie beschikbaar', 'licentie beschikbaar')], default='lange overname', max_length=100),
        ),
    ]
