# Generated by Django 6.0 on 2025-12-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_copyrightitem_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightitem',
            name='infringement',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe'), ('undetermined', 'Undetermined')], default='undetermined', max_length=50),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='possible_fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='copyrightitem',
            name='v2_manual_classification',
            field=models.CharField(choices=[('Ja (open licentie)', 'Ja (Open Licentie)'), ('Ja (eigen werk)', 'Ja (Eigen Werk)'), ('Ja (easy access)', 'Ja (Easy Access)'), ('Nee', 'Nee'), ('Onbekend', 'Onbekend'), ('Ja (bibilotheek licentie)', 'Ja (Bibliotheek Licentie)'), ('Ja (directe toestemming)', 'Ja (Directe Toestemming)'), ('Ja (Publiek domein)', 'Ja (Publiek Domein)'), ('Ja (studentwerk)', 'Ja (Studentwerk)'), ('Ja (anders)', 'Ja (Anders)'), ('Ja (directe toestemming) - tijdelijk', 'Ja (Directe Toestemming) - Tijdelijk'), ('Ja (bibilotheek licentie)- tijdelijk', 'Ja (Bibliotheek Licentie) - Tijdelijk'), ('Ja (anders) - tijdelijk', 'Ja (Anders) - Tijdelijk'), ('Nee (Link beschikbaar)', 'Nee (Link Beschikbaar)'), ('Nee (studentwerk)', 'Nee (Studentwerk)')], db_index=True, default='Onbekend', max_length=100),
        ),
        migrations.AlterField(
            model_name='copyrightitem',
            name='v2_overnamestatus',
            field=models.CharField(choices=[('Overname (inbreukmakende)', 'Inbreukmakend'), ('Overname (andere)', 'Overname (Andere)'), ('Geen overname', 'Geen Overname'), ('Onbekend', 'Onbekend')], default='Onbekend', max_length=100),
        ),
    ]
