# Generated by Django 6.0 on 2025-12-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_copyrightitem_infringement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightitem',
            name='count_students_registered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='course_code',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='course_name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='department',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='manual_identifier',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='pages_x_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='picturecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='reliability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='scope',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
