# Generated by Django 6.0 on 2025-12-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_copyrightitem_manual_classification_and_more'),
        ('documents', '0002_remove_pdfentity_pdf_remove_pdfentity_entity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='documents.document'),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='enrichment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='extraction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='last_enrichment_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
