# Generated by Django 6.0 on 2025-12-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_copyrightitem_count_students_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyrightitem',
            name='in_collection',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copyrightitem',
            name='owner',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
