# Generated by Django 6.0 on 2025-12-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_copyrightitem_document_and_more"),
        ("documents", "0003_alter_document_filehash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copyrightitem",
            name="course_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=2048, null=True
            ),
        ),
        migrations.AlterField(
            model_name="copyrightitem",
            name="department",
            field=models.CharField(
                blank=True, db_index=True, max_length=2048, null=True
            ),
        ),
        migrations.AlterField(
            model_name="copyrightitem",
            name="enrichment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="main_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=2048, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="copyrightitem",
            index=models.Index(
                fields=["url", "file_exists"], name="core_copyri_url_a5ceb6_idx"
            ),
        ),
    ]
