# Generated by Django 6.0 on 2025-12-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_copyrightitem_course_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QlikItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('material_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, db_index=True, max_length=2048, null=True)),
                ('filehash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('filetype', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('doc', 'Word'), ('xlsx', 'Excel'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('author', models.CharField(blank=True, max_length=2048, null=True)),
                ('publisher', models.CharField(blank=True, max_length=2048, null=True)),
                ('period', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, db_index=True, max_length=2048, null=True)),
                ('course_code', models.CharField(blank=True, db_index=True, max_length=2048, null=True)),
                ('course_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('canvas_course_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Unpublished', 'Unpublished'), ('Deleted', 'Deleted')], default='Published', max_length=50)),
                ('classification', models.CharField(choices=[('open access', 'open access'), ('korte overname', 'korte overname'), ('middellange overname', 'middellange overname'), ('lange overname', 'lange overname'), ('eigen materiaal - powerpoint', 'eigen materiaal - powerpoint'), ('eigen materiaal - titelindicatie', 'eigen materiaal - titelindicatie'), ('eigen materiaal - overig', 'eigen materiaal - overig'), ('eigen materiaal', 'eigen materiaal'), ('onbekend', 'onbekend'), ('niet geanalyseerd', 'niet geanalyseerd'), ('in onderzoek', 'in onderzoek'), ('verwijderverzoek verstuurd', 'verwijderverzoek verstuurd'), ('licentie beschikbaar', 'licentie beschikbaar')], default='niet geanalyseerd', max_length=100)),
                ('ml_classification', models.CharField(blank=True, choices=[('open access', 'open access'), ('korte overname', 'korte overname'), ('middellange overname', 'middellange overname'), ('lange overname', 'lange overname'), ('eigen materiaal - powerpoint', 'eigen materiaal - powerpoint'), ('eigen materiaal - titelindicatie', 'eigen materiaal - titelindicatie'), ('eigen materiaal - overig', 'eigen materiaal - overig'), ('eigen materiaal', 'eigen materiaal'), ('onbekend', 'onbekend'), ('niet geanalyseerd', 'niet geanalyseerd'), ('in onderzoek', 'in onderzoek'), ('verwijderverzoek verstuurd', 'verwijderverzoek verstuurd'), ('licentie beschikbaar', 'licentie beschikbaar')], default='niet geanalyseerd', max_length=100, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=2048, null=True)),
                ('in_collection', models.BooleanField(blank=True, null=True)),
                ('picturecount', models.IntegerField(default=0)),
                ('reliability', models.IntegerField(default=0)),
                ('pages_x_students', models.IntegerField(default=0)),
                ('count_students_registered', models.IntegerField(default=0)),
                ('pagecount', models.IntegerField(default=0)),
                ('wordcount', models.IntegerField(default=0)),
                ('retrieved_from_copyright_on', models.DateTimeField(blank=True, null=True)),
                ('last_qlik_update', models.DateTimeField(auto_now=True)),
                ('qlik_source_file', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Qlik Item (Mirror)',
                'verbose_name_plural': 'Qlik Items (Mirror)',
                'db_table': 'qlik_items',
                'indexes': [models.Index(fields=['material_id', 'last_qlik_update'], name='qlik_items_materia_c7499d_idx'), models.Index(fields=['filehash'], name='qlik_items_filehas_07f2e0_idx'), models.Index(fields=['canvas_course_id'], name='qlik_items_canvas__e20e0e_idx'), models.Index(fields=['course_code'], name='qlik_items_course__d991c7_idx')],
            },
        ),
    ]
