# Generated by Django 6.0 on 2025-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_qlikitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qlikitem',
            name='classification',
            field=models.CharField(blank=True, choices=[('open access', 'open access'), ('korte overname', 'korte overname'), ('middellange overname', 'middellange overname'), ('lange overname', 'lange overname'), ('eigen materiaal - powerpoint', 'eigen materiaal - powerpoint'), ('eigen materiaal - titelindicatie', 'eigen materiaal - titelindicatie'), ('eigen materiaal - overig', 'eigen materiaal - overig'), ('eigen materiaal', 'eigen materiaal'), ('onbekend', 'onbekend'), ('niet geanalyseerd', 'niet geanalyseerd'), ('in onderzoek', 'in onderzoek'), ('verwijderverzoek verstuurd', 'verwijderverzoek verstuurd'), ('licentie beschikbaar', 'licentie beschikbaar')], default='niet geanalyseerd', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qlikitem',
            name='filetype',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('doc', 'Word'), ('xlsx', 'Excel'), ('unknown', 'Unknown')], default='unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qlikitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Published', 'Published'), ('Unpublished', 'Unpublished'), ('Deleted', 'Deleted')], default='Published', max_length=50, null=True),
        ),
    ]
