# Generated by Django 6.0 on 2025-12-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrichment", "0002_enrichmentbatch_enrichmentresult_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichmentresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
