# Generated by Django 6.0 on 2025-12-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_missingcourse_itemupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255)),
                ('raw_text', models.CharField(max_length=2048)),
                ('canonical_form', models.CharField(blank=True, max_length=2048, null=True)),
                ('recognized', models.BooleanField(default=False)),
                ('recognition_type', models.CharField(choices=[('Person', 'Person'), ('Organization', 'Organization'), ('Date', 'Date'), ('Location', 'Location'), ('Other', 'Other')], max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='PDFCanvasMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=255)),
                ('folder_id', models.BigIntegerField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=2048)),
                ('filename', models.CharField(max_length=2048)),
                ('upload_status', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('mime_class', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('download_url', models.CharField(max_length=2048)),
                ('size', models.BigIntegerField()),
                ('thumbnail_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('canvas_created_at', models.DateTimeField()),
                ('canvas_updated_at', models.DateTimeField()),
                ('canvas_modified_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField()),
                ('hidden', models.BooleanField()),
                ('lock_at', models.DateTimeField(blank=True, null=True)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('visibility_level', models.CharField(max_length=255)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('user_anonymous_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_display_name', models.CharField(blank=True, max_length=2048, null=True)),
                ('user_avatar_image_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('user_html_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('user_pronouns', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'PDF Canvas Metadata',
            },
        ),
        migrations.CreateModel(
            name='PDFText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('text_quality', models.FloatField(default=0)),
                ('is_ocr', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(blank=True, max_length=2048, null=True)),
                ('url', models.URLField(blank=True, max_length=2048, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('retrieved_on', models.DateTimeField(auto_now_add=True)),
                ('current_file_name', models.CharField(max_length=2048)),
                ('author', models.CharField(blank=True, max_length=2048, null=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('subject', models.CharField(blank=True, max_length=2048, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('producer', models.CharField(blank=True, max_length=2048, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('mod_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=2048, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filehash', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('extraction_attempted', models.BooleanField(default=False)),
                ('extraction_successful', models.BooleanField(default=False)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('num_words', models.IntegerField(blank=True, null=True)),
                ('num_images', models.IntegerField(blank=True, null=True)),
                ('copyright_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf', to='core.copyrightitem')),
                ('v1_copyright_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf', to='core.legacycopyrightitem')),
                ('canvas_metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='documents.pdfcanvasmetadata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDFEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.entity')),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.pdf')),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='extracted_entities',
            field=models.ManyToManyField(related_name='pdfs', through='documents.PDFEntity', to='documents.entity'),
        ),
        migrations.AddField(
            model_name='pdf',
            name='extracted_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf', to='documents.pdftext'),
        ),
    ]
