# Generated by Django 6.0 on 2025-12-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftext',
            name='chunks_with_embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdftext',
            name='detected_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pdftext',
            name='extracted_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
