# Generated by Django 6.0 on 2025-12-18 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfentity",
            name="pdf",
        ),
        migrations.RemoveField(
            model_name="pdfentity",
            name="entity",
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="downloads/%Y/%m/"
                    ),
                ),
                (
                    "original_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                ("filename", models.CharField(blank=True, max_length=2048, null=True)),
                ("author", models.CharField(blank=True, max_length=2048, null=True)),
                ("title", models.CharField(blank=True, max_length=2048, null=True)),
                ("subject", models.CharField(blank=True, max_length=2048, null=True)),
                ("keywords", models.JSONField(blank=True, null=True)),
                ("producer", models.CharField(blank=True, max_length=2048, null=True)),
                ("creation_date", models.DateTimeField(blank=True, null=True)),
                ("mod_date", models.DateTimeField(blank=True, null=True)),
                ("creator", models.CharField(blank=True, max_length=2048, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "filehash",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("extraction_attempted", models.BooleanField(default=False)),
                ("extraction_successful", models.BooleanField(default=False)),
                ("num_pages", models.IntegerField(blank=True, null=True)),
                ("num_words", models.IntegerField(blank=True, null=True)),
                ("num_images", models.IntegerField(blank=True, null=True)),
                (
                    "canvas_metadata",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf",
                        to="documents.pdfcanvasmetadata",
                    ),
                ),
                (
                    "extracted_text",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document",
                        to="documents.pdftext",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.document",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.entity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="extracted_entities",
            field=models.ManyToManyField(
                related_name="documents",
                through="documents.DocumentEntity",
                to="documents.entity",
            ),
        ),
        migrations.DeleteModel(
            name="PDF",
        ),
        migrations.DeleteModel(
            name="PDFEntity",
        ),
    ]
