# Generated by Django 6.0 on 2025-12-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_remove_pdfentity_pdf_remove_pdfentity_entity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="filehash",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
