# Generated by Django 6.0 on 2025-12-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="default_value",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=models.JSONField(),
        ),
    ]
